stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.0-jdk-8-alpine
      shellScript: 'mvn clean package -Dmaven.test.skip=true '
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 192.168.56.102/helloApp:1.0.0
      pushRemote: true
      registry: 127.0.0.1:34985
timeout: 60
notification: {}
